### ISSUE TITLE
Directory not found for new added data

### ISSUE THREAD

**Issue by Faramarz-bagherzadeh** [CryosphereVirtualLab/public-notebooks#11]
Hello, 
I added a .Csv file to "public-notebooks" (which I forked). Now trying to read its data and use it in the notebook. Although the folder is cloned in my notebook, and the CSV file is visible in the directory, I can not catch it.
<img width="921" alt="issue-2" src="https://user-images.githubusercontent.com/61977061/205275244-94829ac0-ab2f-43d0-b3ce-0fde995e07a5.png">

**Comment by ykern** [comment]
Thanks for your question.
I cloned your fork but could not see the changes to the script like you show in the screenshot.
This makes me assume that you are currently not editing the `cvl_get-started.ipynb` of your currently selected directory but maybe in the parent folder or you maybe did not `git push` the changes back to github yet. In your path I see `public-notebooks/public-notebooks/`. Maybe the notebook you are currently editing sits in `public-notebooks/` and not in `public-notebooks/public-notebooks/`.

Otherwise, I assume you are using `import pandas as pd`in the __Import libraries__ section (not visible in your screenshot). 
Then in my case while being in the correct directory the following works:
```python
import pandas as pd
ice_core_data = pd.read_csv('icecore_data.csv')
ice_core_data
```
Results in
![Screenshot 2022-12-02 at 14 42 33](https://user-images.githubusercontent.com/85748520/205306112-1f821d95-0cd2-404d-bb10-82ada176f802.png)

**Comment by Faramarz-bagherzadeh** [comment]
Yes Thanks. I change the directory then it worked (./public-notebooks/icecore_data.csv)
