### ISSUE TITLE
S2 data access

### ISSUE THREAD

**Issue by jlo031** [CryosphereVirtualLab/public-notebooks#35]
I am using the sentinelAPI to search for overlapping S1 and S2 data, then I use the S2 name strings to stitch together the url and access the data with xarray as shown in the example notebook.

For a test case, I get 6 hits for S2 imagery:
S2A_MSIL1C_20220401T151811_N0400_R068_T29XMH_20220401T173711
S2A_MSIL1C_20220401T151811_N0400_R068_T28XEP_20220401T173711
S2A_MSIL1C_20220401T151811_N0400_R068_T29XMJ_20220401T173711
S2B_MSIL1C_20220401T142739_N0400_R139_T29XMH_20220401T165128
S2B_MSIL1C_20220401T142739_N0400_R139_T28XEP_20220401T165128
S2B_MSIL1C_20220401T142739_N0400_R139_T29XMJ_20220401T165128

From these I build the following urls:
https://nbstds.met.no/thredds/dodsC/NBS/S2A/2022/04/01/S2A_MSIL1C_20220401T151811_N0400_R068_T29XMH_20220401T173711.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2A/2022/04/01/S2A_MSIL1C_20220401T151811_N0400_R068_T28XEP_20220401T173711.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2A/2022/04/01/S2A_MSIL1C_20220401T151811_N0400_R068_T29XMJ_20220401T173711.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2B/2022/04/01/S2B_MSIL1C_20220401T142739_N0400_R139_T29XMH_20220401T165128.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2B/2022/04/01/S2B_MSIL1C_20220401T142739_N0400_R139_T28XEP_20220401T165128.nc
https://nbstds.met.no/thredds/dodsC/NBS/S2B/2022/04/01/S2B_MSIL1C_20220401T142739_N0400_R139_T29XMJ_20220401T165128.nc

I try to access the data using xr.open_dataset(url). This works for images 2, 3, 5, and 6 from the above list, but fails for 1, and 4 (netCDF file not found). Any idea what I am doing wrong?

**Comment by ykern** [comment]
I think you are building your URLs correctly. Checking in the catalogue https://nbstds.met.no/thredds/catalog/NBS/S2A/2022/04/01/catalog.html it seems there is just no such file with `T29XMH` for S1. I can only find a file with `T29XNH`. Not sure if that is the one you are looking for, because that would mean that the API would give you `M` instead of `N` or there is an issue with naming somewhere else on either the API or the met server. 

Maybe you can investigate further if you want. Otherwise, I would just omit non-existing files from the API call by adding an `if` loop that skips files that can't be found on the met server.

**Comment by jlo031** [comment]
Thanks for double-checking the URLs. In my notebook, I now simply demonstrate the visualization for one example and write the remaining scene IDs to text file. So I think for the notebook and the demo that is fine for now.

I'll just double-checked the difference between the S2 tiles 29XMH and 29XNH, and they aare different. You can easily check them out here: https://github.com/justinelliotmeyers/Sentinel-2-Shapefile-Index
So I think the APO returns the correct tile, it just doesn't seem to be in the data base somehow?
