### ISSUE TITLE
Data not yet published

### ISSUE THREAD

**Issue by JoMaton** [CryosphereVirtualLab/public-notebooks#7]
Hi, I'm trying to combine two datasets in order to have only one output that will later be published on the CVL 3d visualization portal. One of the dataset is already published but the other one I can only access it as local data and it will be published later on this address: https://data.npolar.no/dataset/1b8631bf-7710-449a-a56f-0da1a4fef608. How would it be possible to deal with this not yet published dataset in the meantime?

**Comment by ykern** [comment]
Thanks for submitting your question. Since the final version of the notebook would be shared and shall be executable by other users, it would be required that all datasets to be used in the workflow are published. This way, the data can be accessed within the notebook (e.g. the way shown in [cvl_get-started.ipynb](https://github.com/CryosphereVirtualLab/public-notebooks/blob/main/cvl_get-started.ipynb)). 

Until the dataset is published you could create a synthetic dataset to be replaced by the real dataset later. As I understand in your situation this is about shape files. In this case you could create a polygon using something like the following ([link to source](https://gis.stackexchange.com/questions/294206/how-to-create-a-simple-polygon-from-coordinates-in-geopandas-with-python)):
```python
import geopandas as gpd
from shapely.geometry import Polygon

lat_point_list = [50.854457, 52.518172, 50.072651, 48.853033, 50.854457]
lon_point_list = [4.377184, 13.407759, 14.435935, 2.349553, 4.377184]

polygon_geom = Polygon(zip(lon_point_list, lat_point_list))
crs = 'epsg:4326'
polygon = gpd.GeoDataFrame(index=[0], crs=crs, geometry=[polygon_geom])       

polygon.to_file(filename='polygon.geojson', driver='GeoJSON')
polygon.to_file(filename='polygon.shp', driver="ESRI Shapefile")
```
Then develop your routine based on this one example - i.e. load the already published dataset and combine it with the synthetic polygon. As soon as the second dataset is published you can then update the script to import it the same way as the first one and instead of the example polygon iterate over all elements of it - i.e. combine all elements of both loaded datasets like originally intended.

**Comment by ykern** [comment]
I hope this helped. We will close the issue for now but feel free to reopen it if things are unclear or if you are still looking for a solution.

**Comment by JoMaton** [comment]
Hi Yannick,
Yes, thank you very much, it helped!
________________________________
